# Generated by Django 4.2.2 on 2023-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_company',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
