# Generated by Django 4.2.2 on 2023-06-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_img', models.ImageField(upload_to='card_img/')),
                ('card_title', models.CharField(max_length=255)),
                ('card_description', models.CharField(max_length=255)),
                ('card_about', models.CharField(max_length=255)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone_number1', models.IntegerField()),
                ('phone_number2', models.IntegerField(blank=True, null=True)),
                ('phone_number3', models.IntegerField(blank=True, null=True)),
                ('card_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cardcategories')),
            ],
        ),
    ]
