# Generated by Django 4.2.2 on 2023-07-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_about',
            field=models.CharField(max_length=5000),
        ),
    ]
