# Generated by Django 4.2.2 on 2023-07-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cardcategories')),
            ],
        ),
    ]
